version: '3'
  services:
    mitmproxy:
      container_name: mitmweb
      ports:
        - '127.0.0.1:8081:8081'
      image: 'mitmproxy/mitmproxy:latest'
      command: 'mitmweb --web-host 0.0.0.0'

    avd:
      container_name: avdocker
      version: api_30
      build:
        context: .
      ports:
        - 3390:3390
        - 5555:5555
